# Generated by Django 3.2.4 on 2022-07-12 18:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('terms', models.TextField(default='')),
                ('privacy', models.TextField(default='')),
                ('note', models.FloatField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.FileField(max_length=254, upload_to=None)),
                ('is_active', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.FileField(max_length=254, upload_to=None)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('image', models.FileField(max_length=254, upload_to=None)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('per_hour_price', models.FloatField(default=0.0)),
                ('description', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('discount_hourly_price', models.FloatField(default=0.0)),
                ('discount_order_limit', models.IntegerField(default=0)),
                ('is_discount_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonalPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('per_hour_price', models.FloatField(default='')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('note', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('slot_name', models.CharField(max_length=128)),
                ('slot_description', models.CharField(max_length=128)),
                ('limit_per_day', models.IntegerField(default=1)),
                ('limit_per_month', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=1024, null=True)),
                ('password', models.CharField(max_length=1024, null=True)),
                ('email', models.CharField(max_length=1024, null=True, unique=True)),
                ('address', models.CharField(max_length=1024, null=True)),
                ('phone', models.CharField(max_length=1024, null=True)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('profile_image', models.CharField(max_length=1024, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Pending'), (3, 'On Verification'), (4, 'Deactivate'), (5, 'Block')], default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('note', models.CharField(max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(default='')),
                ('image', models.FileField(blank=True, default='settings.MEDIA_ROOT/logos/blank.png', max_length=254, upload_to=None)),
                ('price', models.FloatField(default=0.0, max_length=10)),
                ('edition', models.TextField(default='')),
                ('model', models.TextField(default='')),
                ('fuel_type', models.TextField(default='')),
                ('year', models.DateTimeField(default=django.utils.timezone.now)),
                ('transmission', models.TextField(default='')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_ccategory', to='apps.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_category', to='apps.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(default='')),
                ('is_sale', models.BooleanField(default=False)),
                ('group', models.SmallIntegerField(choices=[(1, 'One Day Many Booking'), (2, 'Many Day One Booking')], default=1)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(default='')),
                ('note', models.CharField(max_length=128)),
                ('image', models.FileField(max_length=254, upload_to=None)),
                ('price', models.FloatField(default=0.0, max_length=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_catesgory', to='apps.category')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='food_xcategory', to='apps.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('isWeekly', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=128)),
                ('duration', models.CharField(max_length=128)),
                ('status', models.SmallIntegerField(choices=[(0, 'In Progress'), (1, 'Assigned'), (2, 'Incomplete'), (3, 'Complete')], default=1)),
                ('type', models.SmallIntegerField(choices=[(0, 'Weekly'), (1, 'Monthly'), (2, 'Daily')], default=0)),
                ('option', models.SmallIntegerField(choices=[(0, 'With Material'), (1, 'With Out Material')], default=0)),
                ('lat', models.FloatField(default=0.0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(auto_now=True)),
                ('day', models.TextField(default='')),
                ('start_time', models.TimeField(auto_now=True)),
                ('end_time', models.TimeField(auto_now=True)),
                ('note', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='employee_m', to='apps.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('note', models.CharField(max_length=128)),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('total_cost', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_scxategory', to='apps.user')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_scategory', to='apps.package')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_scxategory', to='apps.timeslot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('text', models.CharField(max_length=128)),
                ('description', models.TextField(default='')),
                ('price', models.FloatField(default=0.0, max_length=10)),
                ('is_winner', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_addj_on', to='apps.user')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cc', to='apps.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
