# Generated by Django 3.2.4 on 2022-07-12 18:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('text', models.CharField(max_length=128)),
                ('description', models.TextField(default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_akkddj_on', to='apps.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
