# Generated by Django 3.2.4 on 2022-07-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='group',
            field=models.SmallIntegerField(choices=[(1, 'Pay Frima'), (2, 'Pickup'), (3, 'Other')], default=3),
        ),
    ]
